name: Run Tests

on:
  push:
    branches:
      - master
      - testing
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x 

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test -- --run

    - name: Run component tests
      run: npm run test:component -- --run

  e2e:
    needs: [test]
    runs-on: windows-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    
    - name: Run E2E tests with WebdriverIO
      run: npm run test:e2e -- --run
