name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install && npm run build

    - name: Run unit tests
      run: npm run test -- --run

    - name: Run component tests
      run: npm run test:component -- --run

    - name: Set up Xvfb (virtual display) for E2E tests
      run: |
        sudo apt-get install -y xvfb
        nohup Xvfb :99 -ac & export DISPLAY=:99

    - name: Run E2E tests with WebdriverIO
      run: npm run test:e2e -- --run
